using StringDetector.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StringDetector.Domain.Services
{
    public class AutoGeneratedKeyService : IAutoGenerateKeyService
    {
        private readonly IEntityRepository<AutoGenerateKeyEntity> _autoKeyRepository;

        public AutoGeneratedKeyService(IEntityRepository<AutoGenerateKeyEntity> autoKeyRepository){
            _autoKeyRepository = autoKeyRepository;
        }



        public int getNextKey()
        {
            AutoGenerateKeyEntity entity= _autoKeyRepository.GetAll().First();
            int nextKey = entity.NextKey;
            entity.NextKey++;
            _autoKeyRepository.Edit(entity);
            return nextKey;
        }

        public bool hasNextKey()
        {
          return _autoKeyRepository.GetAll().First().NextKey<=999999 ? true: false;
        }
    }
}
